### ISSUE TITLE
Move rmw_implementation to the rmw repo

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#10]
Currently this repository contains the `rmw_implementation` package which provides an interface to list and select an implementation for the `rmw` API. It also sets the default implementation. We agreed that it should be in the `rmw` repository as a peer to the `rmw` package instead.

Acceptance Criteria:

- [x] `rmw_implementation` package moved
- [x] git history preserved
- [x] ros2 is still building after the move

**Comment by dirk-thomas** [comment]
It was a bad idea to move it into the `rmw` repository since that generates a bad dependency chain:

    rmw_implementation (in rmw) -> rmw_opensplice_cpp (in rmw_opensplice) -> rwm (in rmw)

That was actually the reason why it was not in the rmw repo before.

**Comment by dirk-thomas** [comment]
![ament_graph](https://cloud.githubusercontent.com/assets/1335366/6540931/3ff298cc-c4b8-11e4-9e1f-95f6a0694bb1.png)

**Comment by dirk-thomas** [comment]
For the same reason `rosidl_default_generators` should be moved out of the `rosidl` repo.

**Comment by wjwwood** [comment]
What's wrong with the dependency chain? Just that you can't easily get `rmw` without the `rmw_implementation` package?

**Comment by dirk-thomas** [comment]
Two repositories depending on each other is a not desired circular dependency.

**Comment by wjwwood** [comment]
Ok, I agree, then what should we do? As I see it we can either move `rmw_implementation` to a different existing repository or move it to its own repository.

I am leaning towards its own repository, but it would be nice to not have yet another repository to deal with.

**Comment by dirk-thomas** [comment]
I share your concern to keep the repo count low. But I don't think it fits well into any of the existing repos and therefore I also lean towards a new separate repo.

**Comment by wjwwood** [comment]
What should we call this repository? Just `rmw_implementation`?

**Comment by dirk-thomas** [comment]
I don't have a better suggestion and would therefore suggest to keep the name as-is.

**Comment by wjwwood** [comment]
The new repository is here: https://github.com/ros2/rmw_implementation

**Comment by wjwwood** [comment]
Ok, I've opened pull requests to address the move. Please review.

**Comment by dirk-thomas** [comment]
lgtm
