### ISSUE TITLE
Real-time safe intra-process communication

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/rclcpp#103]
- [ ] Implement RT allocator and incorporate into examples and demos
- [ ] Implement lock-free synchronization alternative to the mutex in publisher (`intra-process_publish_mutex`) ros2/rclcpp#77
- [x] Extract memory allocations from `take_intra_process_message` and `store_intra_process_message` for pool alternative (solution: allocator template)
- [x] Alternative for `std::map` in `IntraProcessManager` (solution: allocator template for stdlib data structures)
- [ ] Profiling/testing

**Comment by wjwwood** [comment]
Since intra process communication has changed a lot since this was opened, I'll close it.
