### ISSUE TITLE
[rclcpp_action] Progress Toward Quality Level 1

### ISSUE THREAD

**Issue by brawner** [ros2/rclcpp#1036]
This issue tracks the progression of `rclcpp_action` to Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] PRs automatically tested on Jenkins

Documentation
* [x] Per-feature documentation. 
    - Actions described at: https://index.ros.org/doc/ros2/Tutorials/Understanding-ROS2-Actions/
* [x] Per-item documentation in public API. 
    - Doxygen documentation is being generated per release, but the API needs further documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features"
* [x] Tests covering public API
* [x] Code coverage (95%)
    - 76%, see https://ci.ros2.org/job/ci_linux_coverage/37/cobertura/
* [x] Performance tests
* [x] Performance test policy: ROS Core
* [x] Package code style: ROS Core
* [x] Uses ament_lint_common

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - action_msgs
    - rclcpp
    - rcl_action

Platform Support
* [x] Supports all tier 1 platforms

Security

* [x] Vulnerability Disclosure Policy

**Comment by ahcorde** [comment]
Bump QD to level 3 and fixed some links https://github.com/ros2/rclcpp/pull/1158

**Comment by chapulina** [comment]
Reached level 1! :tada: https://github.com/ros2/rclcpp/pull/1477
