### ISSUE TITLE
[rclcpp] Progress Toward Quality Level 1

### ISSUE THREAD

**Issue by brawner** [ros2/rclcpp#1039]
This issue tracks the progression of `rclcpp` to Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] PRs automatically tested on Jenkins

Documentation
* [x] Per-feature documentation. 
    - Many features described in different places, but I couldn't find a single unified location.
* [x] Per-item documentation in public API. 
    - Doxygen documentation is generated
    - Many API components are undocumented
* [x] Declared set of licenses
* [x] Copyright statement in each source file
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features"
* [x] Tests covering public API
* [x] Code coverage (95%)
    - 80%, see https://ci.ros2.org/job/ci_linux_coverage/lastBuild/cobertura/
* [x] Performance tests
* [x] Performance test policy: ROS Core
* [x] Package code style: ROS Core
* [x] Uses ament_lint_common

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - libstatistics_collector
    - rcl
    - rcl_yaml_param_parser
    - rcpputils
    - rcutils
    - rmw
    - statistics_msgs
    - tracetools

Platform Support
* [x] Supports all tier 1 platforms

Security

* [x] Vulnerability Disclosure Policy

**Comment by jacobperron** [comment]
We now have a 1.0.0 release: https://github.com/ros/rosdistro/pull/24844

**Comment by ahcorde** [comment]
Bump QD to level 3 and fixed some links https://github.com/ros2/rclcpp/pull/1158

**Comment by chapulina** [comment]
Level 1 achieved :100: https://github.com/ros2/rclcpp/pull/1477
