### ISSUE TITLE
Expose --params-file option to composable nodes

### ISSUE THREAD

**Issue by dawonn-haval** [ros2/rclcpp#1215]
## Bug report 

Moving from https://github.com/ros2/launch_ros/issues/156

Upgrading from Dashing to Foxy broke my parameter.yaml files that I was using in a composable node. After some debugging I found out that the composable node manager has it's own method for loading parameters from a yaml file that is different from rclcpp's parameter yaml file loader that was used in Dashing. The 'new' file format does not support defining parameters for multiple nodes so I would like to expose the --params-file flag in the component manager service so that the prior logic can be used. 

**Required Info:**
- Operating System: Ubuntu 20.04
- Installation type: Source
- Version or commit hash: 2.0.2, foxy, dc528ad71088ba7a1f2e6f00d4988f9d922a811d
- DDS implementation: Fast-RTPS
- Client library (if applicable): N/A 

#### Steps to reproduce issue
See https://github.com/ros2/launch_ros/issues/156

#### Expected behavior
I should be able to use the params file from dashing with multiple nodes in one file. 

#### Actual behavior
the file format has changed and only a single node per file is possible with the new format.

#### Additional information

Pull request incoming shortly.

**Comment by ivanpauno** [comment]
Closing in favor of https://github.com/ros2/launch_ros/issues/156.
