### ISSUE TITLE
StaticSingleThreadedExecutor's spin_some, spin_all and spin_once cannot use the base class implementation

### ISSUE THREAD

**Issue by brawner** [ros2/rclcpp#1219]
I've been expanding the unit tests of the executors  for all three classes, and these methods in `StaticSingleThreadedExecutor` should not be using the base class implementation in `rclcpp::Executor`. Because `StaticSingleThreadedExecutor` derives and implements its own `add_node` and `remove_node`, the collection of nodes in `rclcpp::Executor` is not updated and so these spin variants won't do any work. Either `add_node` and `remove_node` need to call the base class implementations as well, which would currently throw an "This node already has an executor" exception or these variants need to be derived specifically for `StaticSingleThreadedExecutor`.

**Comment by dirk-thomas** [comment]
@brawner Can you comment what you think should happen on this ticket: assign it to you, assign it to someone else, enhancement for backlog, ...?

**Comment by brawner** [comment]
It's not exactly an enhancement, after dealing with the backport in #1229, I'll assign it to someone else.

**Comment by fujitatomoya** [comment]
i think we can close this by https://github.com/ros2/rclcpp/pull/1338. CC: @mauropasse
