### ISSUE TITLE
allocator memory strategy test failing with CycloneDDS

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclcpp#1268]
The test is failing with CycloneDDS since it was added.

See http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/44/testReport/rclcpp/TestAllocatorMemoryStrategy/number_of_entities_with_subscription/

**Comment by brawner** [comment]
Addressed with #1270
