### ISSUE TITLE
rclcpp memory leak check via valgrind

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/rclcpp#1299]
## Overview

This is a meta-ticket to manage and organize rclcpp test memory leak problems with valgrind.

## Requirement

- Check all of rclcpp test executable with valgrind.
- List all the memory leak issue and address to each one of them.

## Memory Leak List

test executable file | memory leak | Issue | PR | Description
-- | -- | -- | -- | --
./test_allocator_memory_strategy | YES | #1295 | #1296 | Client/Service might be memory leak
./test_create_subscription | YES | #1300 | #1301 | In SubscriptionTopicStatistics, avoid self dependency that not destoryed
./test_executors | YES | #1302 | #1303 | Clear members for StaticExecutorEntitiesCollector to avoid shared_ptr dependency
./test_loaned_message | YES | #1304 | #1305 | Test codes issue: Destroy msg extracted from LoanedMessage
./test_publisher | YES |   |   | The cause is the same as test_subscription
./test_publisher_subscription_count_api | YES |   |   | The cause is the same as test_subscription
./test_static_executor_entities_collector | YES |   |   | The cause is the same as test_executors
./test_subscription | YES | #1306 | #1307 | Not finalize guard condition while destructing SubscriptionIntraProcess
./test_subscription_options | YES |   |   | The cause is the same as test_create_subscription
./test_subscription_topic_statistics | YES |   |   | The cause is the same as test_create_subscription

**Comment by fujitatomoya** [comment]
CC: @Barry-Xu-2018 @iuhilnehc-ynos

**Comment by Barry-Xu-2018** [comment]
@fujitatomoya @iuhilnehc-ynos

Thanks for creating this ticket.   

Currently, we execute rclcpp test and find below memory leak cases.  
    rcl: 511fc40ca305fe075cd53e0b97176cc7be272d69  
    rclcpp: 01d6f52e3281f6df2c191690527f9208006a5c50  
    rmw_fastrtps_cpp: bbe2ac2e3e63c145e9dabd4f073c62d672521a57  

| test executable file | memory leak | Issue | PR |  Description |
|:--|:-:|:--|:--|:--|
| ./test_allocator_memory_strategy                    | YES | #1295 | #1296 | Client/Service might be memory leak  |
| ./test_create_subscription                          | YES | #1300| #1301  | In SubscriptionTopicStatistics, avoid self dependency that not destoryed|
| ./test_executors                                    | YES | | | |
| ./test_loaned_message                               | YES | | | |
| ./test_publisher                                    | YES | | | |
| ./test_publisher_subscription_count_api             | YES | | | |
| ./test_static_executor_entities_collector           | YES | | | |
| ./test_subscription                                 | YES | | | |
| ./test_subscription_options                         | YES | | | |
| ./test_subscription_topic_statistics                | YES | | | |

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 

i think everything's been addressed by now, could you confirm and help to close this one?

**Comment by Barry-Xu-2018** [comment]
@fujitatomoya 

Yeah. Please close it.
