### ISSUE TITLE
Add describe_parameters API to parameter_client

### ISSUE THREAD

**Issue by brawner** [ros2/rclcpp#1354]
Both of the async/sync versions of the ParameterClient do not have API for calling the describe_parameters service, but it seems like it would be a useful addition. The ParameterClient does have an `rclcpp::Client` for the describe_parameters service so this should be straightforward to implement.

**Comment by fujitatomoya** [comment]
CC: @brawner @clalancette 

close this since https://github.com/ros2/rclcpp/pull/1453 is merged.

**Comment by fujitatomoya** [comment]
@brawner 

i thought i opened this one...could you close this?

**Comment by brawner** [comment]
Closed via #1453
