### ISSUE TITLE
Make the lifecycle services optional

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rclcpp#1506]
There is currently no way to not have services attached to the lifecycle node. That prevents an easy setup of a lifecycle management system as each loaded lifecycle node can be individually controlled and thus does not have to go through the management system.
This is a precise use case we see at ros control, where each controller is a lifecycle node but should solely be controlled via the controller manager - not the controller itself - in order to guarantee a proper cleanup and resource management.

see https://github.com/ros-controls/ros2_control/issues/266

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13357)](http://ci.ros2.org/job/ci_linux/13357/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8284)](http://ci.ros2.org/job/ci_linux-aarch64/8284/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11086)](http://ci.ros2.org/job/ci_osx/11086/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13408)](http://ci.ros2.org/job/ci_windows/13408/)

**Comment by Karsten1987** [comment]
CI once more:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13774)](http://ci.ros2.org/job/ci_linux/13774/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8639)](http://ci.ros2.org/job/ci_linux-aarch64/8639/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11482)](http://ci.ros2.org/job/ci_osx/11482/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13851)](http://ci.ros2.org/job/ci_windows/13851/)

**Comment by Karsten1987** [comment]
@fujitatomoya @clalancette What's the final verdict here? We'd like to get this in before the API freeze in order to move forward with ros-control in Galactic. 
It looks like the rcl related PR (ros2/rcl#882) got approved, the rclcpp PR (#1507) is lacking an approval/review.

**Comment by fujitatomoya** [comment]
@Karsten1987 

i will re-visit https://github.com/ros2/rclcpp/pull/1507 in today.

we could use at least another review for both, i guess.

**Comment by Karsten1987** [comment]
one more CI after rebase:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13988)](http://ci.ros2.org/job/ci_linux/13988/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8813)](http://ci.ros2.org/job/ci_linux-aarch64/8813/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11683)](http://ci.ros2.org/job/ci_osx/11683/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14067)](http://ci.ros2.org/job/ci_windows/14067/)

**Comment by Karsten1987** [comment]
With state machine options struct:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14023)](http://ci.ros2.org/job/ci_linux/14023/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8845)](http://ci.ros2.org/job/ci_linux-aarch64/8845/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11718)](http://ci.ros2.org/job/ci_osx/11718/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14110)](http://ci.ros2.org/job/ci_windows/14110/)

**Comment by Karsten1987** [comment]
(hopefully) the last round before merging:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14037)](http://ci.ros2.org/job/ci_linux/14037/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8858)](http://ci.ros2.org/job/ci_linux-aarch64/8858/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11730)](http://ci.ros2.org/job/ci_osx/11730/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14128)](http://ci.ros2.org/job/ci_windows/14128/)

**Comment by Karsten1987** [comment]
closing with #1507 and https://github.com/ros2/rcl/pull/882
