### ISSUE TITLE
rclcpp lifecycle: refine design of init, shutdown

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/rclcpp#154]
See discussion on ros2/rclcpp#152

**Comment by Karsten1987** [comment]
closing this as the related PR is closed.

**Comment by wjwwood** [comment]
I don't think this was the right action, as the related PR was closed (declined) but the topic is still an issue, see: https://discourse.ros.org/t/how-to-shutdown-and-reinitialize-a-publisher-node-in-ros-2/4090/1f

**Comment by wjwwood** [comment]
We could clean this issue up and make it clearer what needs to be done.

**Comment by wjwwood** [comment]
I think this was addressed in https://github.com/ros2/rclcpp/pull/587.
