### ISSUE TITLE
What is "oh yeah destructuro"

### ISSUE THREAD

**Issue by BriceRenaudeau** [ros2/rclcpp#1601]
## Bug report

Useless messages appear when killing a lifecycle node.

**Required Info:**

- Operating System:
Ubuntu
- Installation type:
Binary
- Version or commit hash:
master
- DDS implementation:
Cyclone
- Client library (if applicable):
lifecycle_node_interface

#### Steps to reproduce the issue
When killing my lifecycle node "assisted_teleop" this message appears:

```
[assisted_teleop-28] [INFO] [1617022166.929935526] [assisted_teleop.local_costmap]: Destroying
[assisted_teleop-28] oh yeah destructuro
[assisted_teleop-28] oh yeah end destructuro
[assisted_teleop-28] oh yeah end destructuro222
[assisted_teleop-28] oh yeah destructuro
[assisted_teleop-28] oh yeah end destructuro
[assisted_teleop-28] oh yeah end destructuro222
```

#### Expected behavior
Only the message "Destroying" should appear

#### Additional information
Error comes from here:
https://github.com/ros2/rclcpp/blob/052596c971c1767155bdcbce573bd52a445c9ea2/rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp#L64-L76

**Comment by christophebedard** [comment]
It was introduced by https://github.com/ros2/rclcpp/pull/1507. Seems like it was just left behind and no one caught it.

**Comment by Karsten1987** [comment]
lol. Now y'all know my advanced debugging techniques ;-)

Thanks @ivanpauno for taking care of it!

**Comment by fujitatomoya** [comment]
lol 😆
