### ISSUE TITLE
Support a bunch of SingleThreadedExecutor with dedicated thread for each component nodes

### ISSUE THREAD

**Issue by gezp** [ros2/rclcpp#1772]
#### Feature description

Hi, guys

I'm working on project [Reduce ROS2 Nodes and Determinism](https://navigation.ros.org/2021summerOfCode/projects/spinners.html) of OSPP2021 (under the mentor of Steve Macenski).

Currently, i'm trying to support composed bringup for Nav2 stack, and i have done some works about manually composed bringup (`Compile-time composition`) of Nav2, which performs better than Normal bringup , in addition, i find a problem that  `a large multi-threaded executor` consumes higher cpu(increase 30%-50%) than `a bunch of single-threaded executors` , you can find some details here: https://discourse.ros.org/t/nav2-composition/22175. 

for `Run-time composition` , i notice that `rclcpp_components` only provides `component_container` which use `SingleThreadedExecutor` for all component nodes in container and `component_container_mt` which use `MultiThreadedExecutor`.  

how about supporting a bunch of `SinglethreadedExecutor` for  `component_container` ?  in other word, create a `SingleThreadedExecutor` with dedicated thread for each component nodes.

Edited : clean some irrelevant topic.

**Comment by SteveMacenski** [comment]
@gezp please propose the simplified design we chatted about to the maintainers. I'm sure just the parameter + simplified needs we directly have can be accommodated without much concern.

**Comment by gezp** [comment]
@SteveMacenski , i have cleaned this ticket, and open a new ticket for another topic: https://github.com/ros2/rclcpp/issues/1774.

**Comment by SteveMacenski** [comment]
Should this be closed then?
