### ISSUE TITLE
NodeOptions is not a member of rclcpp

### ISSUE THREAD

**Issue by sandhavel** [ros2/rclcpp#1780]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 18.04

#### Steps to reproduce issue

```

```

#### Expected behavior
Finished <<< lifecycle (package)

#### Actual behavior
Failed   <<< lifecycle [27.6s, exited with code 2]
with "error: ‘NodeOptions’ is not a member of ‘rclcpp’
       rclcpp::NodeOptions().use_intra_process_comms(intra_process_comms))"
----
#### Implementation considerations

![Screenshot from 2021-09-22 15-50-18](https://user-images.githubusercontent.com/91118175/134327337-53ab46a5-964b-4b16-99b0-1c1906bdc49a.png)

ERROR:
When i am running this command "colcon build --symlink-install"

"error: ‘NodeOptions’ is not a member of ‘rclcpp’
       rclcpp::NodeOptions().use_intra_process_comms(intra_process_comms))"

**Comment by clalancette** [comment]
What steps did you use to checkout ros2, and what branch are you on?  It looks like you are either on the wrong branch, or haven't sourced the underlay with rclcpp properly.

**Comment by sandhavel** [comment]
> What steps did you use to checkout ros2, and what branch are you on? It looks like you are either on the wrong branch, or haven't sourced the underlay with rclcpp properly.

wget https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos

**Comment by clalancette** [comment]
> wget https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos

Sorry, you'll need to provide more information.  We know this works for us (we run it nightly in CI), so there is something about your environment that is different.

**Comment by sandhavel** [comment]
https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html

I follow the steps, which is mentioned in above link, when i run colcon build --symlinnk-install, that error occurs

**Comment by sandhavel** [comment]
even i used  https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos ,
the same error occurs...
