### ISSUE TITLE
Create subscriptions that automatically detects the publishers' QoS

### ISSUE THREAD

**Issue by fmrico** [ros2/rclcpp#1835]
## Feature request

A `create_subscription` method to `Node` that adapts to the publisher's QoS

#### Feature description

IMHO it will be useful to add a `create_subscription` method to `Node` in which no QoS is specified. Currently, it is possible to get the publisher(s) QoS.  This method could retrieve the publisher's QoS and use it for creating the subscription. 

The goal of this PR is to make it easier for new (and vets) ROS2 developers to start working with QoS. Maybe the QoS incompatibilities are one of the first frustrations...

#### Implementation considerations

1. The method could be:

```
std::shared_ptr< SubscriptionT > create_subscription (const std::string &topic_name, CallbackT &&callback, const SubscriptionOptionsWithAllocator< AllocatorT > &options=SubscriptionOptionsWithAllocator< AllocatorT >(), typename MessageMemoryStrategyT::SharedPtr msg_mem_strat=(MessageMemoryStrategyT::create_default()))
```

2. If there is not any publisher yet, use the default QoS (volatile+reliable)
3. If there is more than one publisher, with a different QoS, I would show a warning, and select the first one.
4. **I can work on this PR if you think it would be useful.**

**Comment by fujitatomoya** [comment]
IMO, i think basically QoS needs to be considered in application endpoints based on the use cases. auto-adjustment introduces racy condition that could lead to inconsistent behavior in the distributed application. besides, there are several pre-defined QoS sets provided.
