### ISSUE TITLE
error: ‘WaitSet’ is not a member of ‘rclcpp’

### ISSUE THREAD

**Issue by TianchaoHuo** [ros2/rclcpp#1854]
Hi, 

when I try to use wait_set in my code [ copied from this link](https://answers.ros.org/question/307370/ros2-whats-the-best-way-to-wait-for-a-new-message/)

```c++
#include <rclcpp/rclcpp.hpp>
rclcpp::WaitSet wait_set;
wait_set.add_subscription(subscription);
auto ret = wait_set.wait(std::chrono::seconds(10));
if (ret.kind() == rclcpp::WaitResultKind::Ready) {
  std_msgs::msg::String msg;
  rclcpp::MessageInfo info;
  auto ret_take = subscription->take(msg, info);
  if (ret_take) {
    RCLCPP_INFO(this->get_logger(), "got message: %s", msg.data.c_str());
  } else {
    RCLCPP_ERROR(this->get_logger(), "no message received");
  }
} else {
  RCLCPP_ERROR(this->get_logger(), "couldn't wait for message");
}
```
I face a problem : 
error: ‘WaitSet’ is not a member of ‘rclcpp’
         rclcpp::WaitSet  wait_set;`

How can I solve this problem? thanks in advance.

**Comment by clalancette** [comment]
Please ask questions like this on https://answers.ros.org, which is the central question and answer site.  You'll get a better answer there.  Closing this out.
