### ISSUE TITLE
what is ::SharedPtr

### ISSUE THREAD

**Issue by hyuny223** [ros2/rclcpp#1879]
Hello.
I have a question.

what is "::SharedPtr"?

I know that it is one of types.

It is used for something that returns shared pointer.

what I want to know is that how is it defined and how would it work etc. 

I have been trying to search for it in this page or google, but I couldn't find it.

thanks!

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org , which is our central question-and-answers site.
