### ISSUE TITLE
bugprone-exception-escape in node_main.cpp.in

### ISSUE THREAD

**Issue by alsora** [ros2/rclcpp#1890]
## Bug report

Hi, running clang-tidy on a project that uses rclcpp_components causes a bugprone exception escape error in the automatically generated main files (`node_main.cpp.in`).

```
warning: an exception may be thrown in function 'main' which should not throw exceptions [bugprone-exception-escape]
```

Not sure which line can cause an exception, probably either the factory or the class loader.

**Comment by fujitatomoya** [comment]
@alsora https://github.com/ros2/rclcpp/pull/1894 does this help to quiet the warning?
