### ISSUE TITLE
:man_farmer: Windows test failures on `test_subscription_content_filter.cpp`

### ISSUE THREAD

**Issue by Blast545** [ros2/rclcpp#1912]
## Bug report

**Required Info:**

- Operating System:
  - Windows
- Installation type:
  - Source, buildfarm
- Version or commit hash:
  - main
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Run a buildfarm nightly_win_rel job.

#### Expected behavior
Test passes.

#### Actual behavior
Test fails.

#### Additional information
Error log:
```
C:\ci\ws\src\ros2\rclcpp\rclcpp\test\rclcpp\test_subscription_content_filter.cpp:200
Value of: receive
  Actual: false
Expected: true

C:\ci\ws\src\ros2\rclcpp\rclcpp\test\rclcpp\test_subscription_content_filter.cpp:201
Expected equality of these values:
  original_message
    Which is: 48-byte object <00-00 00-4E 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 03-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
  output_message
    Which is: 48-byte object <00-00 00-4E 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
```

Link to the errors:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/2261/testReport/junit/rclcpp/TestContentFilterSubscription/content_filter_get_begin/
https://ci.ros2.org/view/nightly/job/nightly_win_rel/2261/testReport/junit/rclcpp/TestContentFilterSubscription/content_filter_get_later/

PR introducing this regression: 
https://github.com/ros2/rclcpp/pull/1561

**Comment by iuhilnehc-ynos** [comment]
Fixed by https://github.com/ros2/rmw_connextdds/pull/81

**Comment by clalancette** [comment]
Since this one is fixed now, I'm going to go ahead and close it out.  Feel free to reopen if it occurs again.
