### ISSUE TITLE
Mismatch between documentation and implementation of rclcpp::ParameterEventHandler::get_parameter_from_event

### ISSUE THREAD

**Issue by viccie30** [ros2/rclcpp#1921]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - 9.2.0-1focal.20220211.031858
- DDS implementation:
  - N/A
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Call `rclcpp::ParameterEventHandler::get_parameter_from_event(const rcl_interfaces::msg::ParameterEvent & event, const std::string parameter_name, const std::string node_name)` for a non-existent parameter.

#### Expected behavior
According to https://github.com/ros2/rclcpp/blob/c24e485084f421292734ebf6b63f1a105a2c7602/rclcpp/include/rclcpp/parameter_event_handler.hpp#L263-L265, if the requested parameter is not found, a not-set Parameter is returned.

#### Actual behavior
The function throws an exception and does not return normally. See https://github.com/ros2/rclcpp/blob/c24e485084f421292734ebf6b63f1a105a2c7602/rclcpp/src/rclcpp/parameter_event_handler.cpp#L135-L139.

#### Additional information
None

**Comment by jacobperron** [comment]
Fixed in https://github.com/ros2/rclcpp/pull/1922
