### ISSUE TITLE
[question] Is it possible to use `rclcpp` without Colcon?

### ISSUE THREAD

**Issue by hwhsu1231** [ros2/rclcpp#1942]
In ROS2 documentations and tutorials, they all use Colcon or its alternatives to configure and build the projects. 

I was wondering whether it is possible to use ROS-related SDKs or APIs without Colcon. For example, I want to use them with CMake. It is because we already have lots of IDEs, which support CMake.

I understand that the evolution of Colcon and its ancestors and their purposes. But, since `rclcpp` is a C++ library as the `README.md` describe, is it possible to use it with pure CMake tools?

**Comment by clalancette** [comment]
For questions like this, please use https://answers.ros.org, which is our central question and answer site.  If you @ me in that post, I'll respond over there.
