### ISSUE TITLE
[Question] Possible in rclcpp to create syncparameter service with rcl_node_t?

### ISSUE THREAD

**Issue by carTloyal123** [ros2/rclcpp#1961]
## QUESTION

**Required Info:**

- Operating System:
  - Windows 10, Ubuntu 20.04 Docker image, ROS2 Humble
- Installation type:
  - Binary installation
- DDS implementation:
  - Default
- Client library (if applicable):
  - rclcpp

#### Question description
Is it possible to create a syncparametersclient using just the base rcl_node_t? I am fairly new to using raw rclcpp library calls but I can not seem to find an answer to do the following:

Setup:
~~~
rcl_node_t node;
rc = rcl_node_init(&node, "namespace_name", "node_name", context, &opts);
if (rc != RCL_RET_OK)
{
  RCLCPP_ERROR(rclcpp::get_logger("logger"), "RCL Node Init falied!");
}

~~~
Can I do this somehow?
~~~
auto rcl_param_client = std::make_shared<rclcpp::SyncParametersClient>(node, "");
auto loaded_params = rcl_param_client->load_parameters("config/config_file.yaml");
~~~

I want to be able to load parameters to the node easily through a yaml which is easy and automatic when using rclcpp::Node but when constructing nodes from scratch I does not appear obvious if this is possible or even plausible. Any input is appreciated! I am programatically constructing nodes, publishers, and subscribers which is why I am constrained to using rcl_node_t for setup.

#### Implementation considerations
Possible able to add a constructor to rclcpp::SyncParametersClient that takes in node templates rcl_node_t? Not too sure about that solution though.

Thank you!

**Comment by alsora** [comment]
Hi, I recommend to ask this kind of questions on the ros answers website: https://answers.ros.org/questions/

It is not possible to construct rclcpp entities from a rcl node object.
The recommended way for creating entities in the ROS 2 graph is to first define a new class that inherits from rclcpp::Node and inside this class create all the publishers/subscriptionz/clients that you need.

See an example about using parameter clients here https://github.com/ros2/demos/blob/master/demo_nodes_cpp/src/parameters/set_and_get_parameters_async.cpp
