### ISSUE TITLE
Use Parameter Client to declare not existing parameter to remotely node

### ISSUE THREAD

**Issue by ipa-rwu** [ros2/rclcpp#1966]
#### Feature description

I would like to set a value to a parameter of a remote node. But this parameter does not exist yet.
I tried `set_parameters`
https://github.com/ros2/rclcpp/blob/206e0fd4fefb9fcf69d42c03ffbefd347f110aae/rclcpp/include/rclcpp/parameter_client.hpp#L146-L150
from AsyncParametersClient. But it doesn't work.

From the test case
https://github.com/ros2/rclcpp/blob/33dae5d679751b603205008fcb31755986bcee1c/rclcpp/test/rclcpp/test_parameter_client.cpp#L292-L313),
it only can set values to existing parameters. 

Is there any reason why there is no function like `declare_parameter`? 

Thank you for your help!

**Comment by clalancette** [comment]
The remote node needs to have `allow_undeclared_parameters` set in order for it to accept new parameters.  See https://github.com/ros2/demos/blob/rolling/demo_nodes_cpp/src/parameters/parameter_blackboard.cpp as an example on how to do that.

In the future, for questions like this please ask them on https://answers.ros.org, which is our central Question and Answer site.  That way the answer will be searchable.
