### ISSUE TITLE
management of subscribers/publishers

### ISSUE THREAD

**Issue by BobDean** [ros2/rclcpp#2]
Not sure if this is the way to make a comment or not, so please forgive. 

Why should create_X return a handle for a publisher or subscriber when that information can be managed internally? What flexibility does it provide? Most topics are openend/closed at start/shutdown, with a single type on a single topic.  With the current mechanism, there are 3 APIs: node, publish, subscribe.  If the Node manages the publishers and subscribers, there would be a single API handling create/read/write, fewer objects for the client to track, and potentially a simpler locking and management scheme in a multi-threaded environment.

**Comment by tfoote** [comment]
Sorry wrong button

**Comment by wjwwood** [comment]
@BobDean I'm going to close this since I think most of the questions were addressed. We can continue the conversation or move it to the sig ng mailing list.
