### ISSUE TITLE
Implement wait_for_service

### ISSUE THREAD

**Issue by gerkey** [ros2/rclcpp#201]
We need an equivalent of [roscpp::waitForService()](http://docs.ros.org/jade/api/roscpp/html/namespaceros_1_1service.html#aabe996581255345b3383e66eaaedef5a), which waits a bounded amount of time for a service server to become available. It should be possible to build it atop [Node::count_subscribers()](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/node.hpp#L249). Ideally it will internally be done in an event-driven manner, rather than polling.

**Comment by gerkey** [comment]
Superseded by ros2/ros2#215

**Comment by wjwwood** [comment]
I'm going to close this again, in favor of https://github.com/ros2/ros2/issues/215.
