### ISSUE TITLE
Question: Logging in ROS 2

### ISSUE THREAD

**Issue by firesurfer** [ros2/rclcpp#203]
Is there already any logging mechanism implemented in ROS 2 one can use to log messages to a certain topic like in ROS 1 ( http://wiki.ros.org/roscpp/Overview/Logging ) ?

**Comment by dirk-thomas** [comment]
No, currently there is nothing like that. But looking into the general API for logging (at least to the console) is on the list of the current alpha cycle: ros2/ros2#198
