### ISSUE TITLE
Creating subscription and binding the callback in cpp library.

### ISSUE THREAD

**Issue by AmmarAlbakri** [ros2/rclcpp#2095]
#### Feature description
I am trying to implement a subscription in my cpp library (hardware interface, not an actual node but I am inheriting the rclcpp:Node class), the topic seems to be created but the callback function is not bound and I can't receive messages on it.

#### Implementation considerations
Maybe there is a way to do that with executes (based on this [post](https://answers.ros.org/question/403073/ros2-subscriber-in-component/)) but I can't find the solution on my own. If there is a way please add it to the documentation.

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
