### ISSUE TITLE
Failed to initialize rcl: error not set

### ISSUE THREAD

**Issue by Tyce11** [ros2/rclcpp#2262]
- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Debian packages 
- Version or commit hash:
  - Humble
- DDS implementation:
  - rmw_microxrcedds

#### Steps to reproduce issue
- Download ros2 following this guide: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html
- Run the demo at the end of the tutorial `ros2 run demo_nodes_cpp talker
`

#### Expected behavior
- Demo runs as expected

#### Actual behavior
- Terminal returns the error: `terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl: error not set, at ./src/rcl/init.c:218
[ros2run]: Aborted
`

#### Additional information
- I first discovered the issue while trying to run `ros2 topic list`. It returned the same error. I then reinstalled ros2 and when I got to the end it continued to give the same error.

**Comment by clalancette** [comment]
> * rmw_microxrcedds

This isn't one of the RMWs we support.  I think you'll need to open a ticket with the microROS folks at https://github.com/micro-ROS/rmw_microxrcedds
