### ISSUE TITLE
When the binary package will be released to Humble?

### ISSUE THREAD

**Issue by Nicky-Kim-A** [ros2/rclcpp#2310]
When will the next binary package be released to Humble?  
I'm awaiting the next release, including [this backporting commit ](https://github.com/ros2/rclcpp/commit/689e510cf0d58257752127750b6460f1f66872c5)to fix the ["Unhandled Termination" problem](https://github.com/ros2/ros2/issues/1253).

**Comment by audrow** [comment]
Hi @Nicky-Kim-A, I'm going to do another Humble patch next week.

**Comment by audrow** [comment]
Here's the patch: https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2023-09-25/33734
