### ISSUE TITLE
Question - Possible to build deb packages at the moment?

### ISSUE THREAD

**Issue by firesurfer** [ros2/rclcpp#235]
Is it possible to build deb packages of ros2 at the moment without doing the packaging by hand? I want to distribute updates of ros2 to a rack of raspberry pi's.  

What way would you suggest in order to build deb packages of my own software that is build on top of ros2 ?

**Comment by wjwwood** [comment]
We don't have infrastructure for debs yet. You could use something like
checkinstall though.

https://debian-administration.org/article/147/Installing_packages_from_source_code_with_checkinstall

On Monday, July 4, 2016, Lennart Nachtigall <notifications@github.com>
wrote:

> Is it possible to build deb packages of ros2 at the moment without doing
> the packaging by hand? I want to distribute updates of ros2 to a rack of
> raspberry pi's.
>
> What way would you suggest in order to build deb packages of my own
> software that is build on top of ros2 ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros2/rclcpp/issues/235>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAGIS3WDlh-OLmwb6yOXkd-XpWj9WSJbks5qSVqEgaJpZM4JEm_A>
> .
>


-- 
William Woodall
ROS Development Team
william@osrfoundation.org
http://wjwwood.io/
