### ISSUE TITLE
ROS2 DOWNLOAD LINK NOT WORKING #ROS2

### ISSUE THREAD

**Issue by MRChamp001** [ros2/rclcpp#2385]
This command is not working 
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
I have proper internet, and system is ubuntu 22.04
Please help

**Comment by alsora** [comment]
Hi @MRChamp001, this issue has nothing to do with this repository.

If you have questions about how to build/install ROS 2 please use the robotics stack exchange forum https://robotics.stackexchange.com/
