### ISSUE TITLE
Add a "wait for parameter server" to be ready method

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#249]
The parameter client should have a way to wait for a parameter server to be available before trying to set/get/list parameters from it. Without this we cannot write deterministic tests, see:
- https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/51#issuecomment-242872096
- https://github.com/ros2/system_tests/pull/159

The changes in https://github.com/ros2/system_tests/pull/159 should be removed once this function is added and used in its place.

**Comment by dhood** [comment]
closed by https://github.com/ros2/rclcpp/pull/342 and https://github.com/ros2/rclcpp/pull/356 (adding features), and https://github.com/ros2/system_tests/pull/219 (updating tests)
