### ISSUE TITLE
Regression : Executor::spin_some_impl is active waiting

### ISSUE THREAD

**Issue by jmachowinski** [ros2/rclcpp#2508]
This was introduced in #2142

https://github.com/ros2/rclcpp/blob/3d58f0fb703d86461c2ab2fb39cd2640dc26e219/rclcpp/src/rclcpp/executor.cpp#L383

This condition make the executor active spin until the time is over if used in spin_all.

I guess 
```c++
    if (!wait_result_.has_value() || !exhaustive) {
      // In the case of spin some, then we can exit
      // In the case of spin all, then we will allow ourselves to wait again.
      break;
    }
``` 
is the correct implementation.

**Comment by MichaelOrlov** [comment]
@wjwwood Could you please handle this issue? 
We decided to assign this issue to you at the latest waffle meeting. However, I don't have permission to change the Assignee field.

**Comment by wjwwood** [comment]
Small update, I've iterated on the original pr to fix this here: https://github.com/ros2/rclcpp/pull/2517

Waiting to get it reviewed before merging it.

**Comment by fujitatomoya** [comment]
@wjwwood i will try to taka a look in this week. thanks!

**Comment by wjwwood** [comment]
Thanks @fujitatomoya, as always more reviews (even post merge reviews) are welcome, but @mjcarroll reviewed it already too.

**Comment by wjwwood** [comment]
Closed with https://github.com/ros2/rclcpp/pull/2517
