### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xuefengchang** [ros2/rclcpp#257]
when I compile my code, I got the following errors:
ros2_ws/install/lib/librclcpp.so: undefined reference to symbol 'rcl_get_default_allocator'
ros2_ws/install/lib/librcl__rmw_fastrtps_cpp.so: error adding symbols: DSO missing from command line
how to solve this problem？

**Comment by firesurfer** [comment]
Could you post your CMakeLists.txt ?

**Comment by dirk-thomas** [comment]
Closing this ticket for no response. Please feel free to comment on the closed ticket with more information and it can be reopened.
