### ISSUE TITLE
:farmer: TestServiceIntrospection.service_introspection_enable_disable_events failing in Rolling, Jazzy and Iron Connext

### ISSUE THREAD

**Issue by Crola1702** [ros2/rclcpp#2613]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Noble
- Installation type:
  - Source
- Version or commit hash:
  - Rolling
- DDS implementation:
  - RTI Connext
- Client library (if applicable):
  - Rclcpp

#### Steps to reproduce issue
1. Run a build in [Rci__nightly-connext_ubuntu_noble_amd64](https://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/)
2. See test regression fail

#### Additional information

Reference build:
* [projectroot.test.rclcpp.test_service_introspection](https://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/124/testReport/junit/projectroot.test/rclcpp/test_service_introspection/)
* [rclcpp.TestServiceIntrospection.service_introspection_enable_disable_events](https://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/124/testReport/junit/rclcpp/TestServiceIntrospection/service_introspection_enable_disable_events/)
* [rclcpp.TestServiceIntrospection.service_introspection_enable_disable_event_content](https://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/176/testReport/junit/rclcpp/TestServiceIntrospection/service_introspection_enable_disable_event_content/)

Log output:
```
[ RUN      ] TestServiceIntrospection.service_introspection_enable_disable_events
RTI Connext DDS Non-commercial license is for academic, research, evaluation and personal use only. USE FOR COMMERCIAL PURPOSES IS PROHIBITED. See RTI_LICENSE.TXT for terms. Download free tools at rti.com/ncl. License issued to Non-Commercial User license@rti.com For non-production use only.
Expires on 00-jan-00 See www.rti.com for more information.
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_service_introspection.cpp:201: Failure
Expected equality of these values:
  events.size()
    Which is: 1
  2U
    Which is: 2

/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_service_introspection.cpp:218: Failure
Expected equality of these values:
  events.size()
    Which is: 3
  4U
    Which is: 4

[  FAILED  ] TestServiceIntrospection.service_introspection_enable_disable_events (3309 ms)
[ RUN      ] TestServiceIntrospection.service_introspection_enable_disable_event_content
RTI Connext DDS Non-commercial license is for academic, research, evaluation and personal use only. USE FOR COMMERCIAL PURPOSES IS PROHIBITED. See RTI_LICENSE.TXT for terms. Download free tools at rti.com/ncl. License issued to Non-Commercial User license@rti.com For non-production use only.
Expires on 00-jan-00 See www.rti.com for more information.
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_service_introspection.cpp:340: Failure
Expected equality of these values:
  events.size()
    Which is: 3
  4U
    Which is: 4

[  FAILED  ] TestServiceIntrospection.service_introspection_enable_disable_event_content (1307 ms)
```

It's a flaky with a high percentage failure rate:
job_name|last_fail|first_fail|build_count|failure_count|failure_percentage
-- | -- | -- | -- | -- | --
Ici__nightly-connext_ubuntu_jammy_amd64|2024-08-28|2024-08-14|6|4|66.67
Rci__nightly-connext_ubuntu_noble_amd64|2024-08-27|2024-08-14|12|11|91.67
Jci__nightly-connext_ubuntu_noble_amd64|2024-08-26|2024-08-13|6|5|83.33

**Comment by fujitatomoya** [comment]
@fgallegosalido this test also fails with rmw_connextdds only, can you take a look at my comment on https://github.com/ros2/rclcpp/pull/2651? i was trying to address this unstable problem, but it does not work as expected.

**Comment by fgallegosalido** [comment]
I will look into it and let you know what I find.

**Comment by fujitatomoya** [comment]
@fgallegosalido just checking, any updates on this?

**Comment by fgallegosalido** [comment]
@fujitatomoya sorry, not much was done. I was able to reproduce the issue and started working on it, but couldn't find the root cause, so I moved to do other things. I will resume the work on it as soon as possible

**Comment by fujitatomoya** [comment]
@fgallegosalido no worries, thanks for working on this. i will revisit https://github.com/ros2/rclcpp/pull/2651 to see if i can find some clue on this.
