### ISSUE TITLE
rclcpp_action::ClientBase::SharedPtr is aliased to rclcpp::Waitable

### ISSUE THREAD

**Issue by taDachs** [ros2/rclcpp#2630]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  - 
- DDS implementation:
  - Cyclone
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```cpp
rclcpp_action::ClientBase::SharedPtr test;
&(test->action_server_is_ready);
```

#### Expected behavior
`rclcpp_action::ClientBase::SharedPtr` is a shared ptr to `ClientBase`

#### Actual behavior

`rclcpp_action::ClientBase::SharedPtr` is a shared ptr to `Waitable`

#### Additional Info

It looks like `ServerBase` and `ClientBase` for `rclcpp_action` are both missing the `RCLCPP_SMART_PTR_DEFINITIONS_NOT_COPYABLE` macro.

**Comment by alsora** [comment]
Thanks for the report.
I opened a PR that should fix the problem.
