### ISSUE TITLE
has_invalid_weak_nodes can only ever be false

### ISSUE THREAD

**Issue by gbiggs** [ros2/rclcpp#264]
In allocator_memory_strategy.hpp in the function `collect_entities`, the variable `has_invalid_weak_nodes` looks to me like it can only ever be `false`.

https://github.com/ros2/rclcpp/blob/7494350ad24201bd0ef6f75b94760830948274cb/rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp#L143

Is the correct behaviour for line 147 to set the value to `true`?

**Comment by wjwwood** [comment]
I think this line is wrong:

https://github.com/ros2/rclcpp/blob/7494350ad24201bd0ef6f75b94760830948274cb/rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp#L147

It should be `= true` here.

**Comment by wjwwood** [comment]
Think you could open a pr that fixes that? I think it means that essentially no invalid nodes are ever removed from this list:

https://github.com/ros2/rclcpp/blob/f28bb1107881a983efef78d5022a257e3b09eda4/rclcpp/src/rclcpp/executor.cpp#L331-L346
