### ISSUE TITLE
Callback delay when adding a node

### ISSUE THREAD

**Issue by Masa0u0** [ros2/rclcpp#2642]
When a new node is added, the network traffic increases, and the callback delay of each node becomes significant, which is problematic. I learned that using a Discovery Server could improve this, but is it possible to separate the threads handling the callback functions from those handling the DDS connections in the first place?

**Comment by fujitatomoya** [comment]
What does it mean `the callback` by here? is that user callbacks executed by Executor? if that is so,

> but is it possible to separate the threads handling the callback functions from those handling the DDS connections in the first place?

User application owns the executor and those threads to take and execute the data from RMW implementation, that means DDS (RWM Implementation) does not use the same thread from use's executor. i think that this depends on the RMW implementation details, i.e https://fast-dds.docs.eprosima.com/en/latest/fastdds/library_overview/library_overview.html#concurrency-and-multithreading

ASAIK, this is not the issue with rclcpp or ROS 2 libraries, i would recommend that posting this kind of question to https://robotics.stackexchange.com/ where is our centralized QA site.
