### ISSUE TITLE
Segfault using MultiThreadedExecutor and LifecycleNode with rmw_fastrtps_cpp

### ISSUE THREAD

**Issue by DiogoRoseira** [ros2/rclcpp#2677]
### Bug report:

---

**Operating System:**

- Ubuntu 22.04

**Installation type:**

- Binaries

**Version or commit hash:**

- The latest available binaries on Humble

**DDS implementation:**

- rmw_fastrtps_cpp

**Client library (if applicable):**

- rclcpp, rclcpp_lifecycle

### Problem

Im having the same issue reported here, https://github.com/ros2/demos/issues/654. 

**Probable cause** can be the issue on, https://github.com/ros2/rclcpp/issues/2664

I can resolve using the `cyclonedds` but i would know if it was possible to use `fastdds`

**Comment by fujitatomoya** [comment]
@DiogoRoseira I will go ahead to lose this issue because you already mentioned that https://github.com/ros2/rclcpp/issues/2664 is the same issue. feel free to reopen if needed but we would not want to duplicated issued else where.
