### ISSUE TITLE
Certain service names result into service call failure

### ISSUE THREAD

**Issue by firesurfer** [ros2/rclcpp#294]
I realized that certain names result into failing service calls if more than one service with this naming pattern was created. 

I created an example: https://github.com/firesurfer/service_name_demo

This probably also resolves #256

**Comment by dirk-thomas** [comment]
Can you please describe what behavior you are seeing and how "this" resolves 256.

**Comment by firesurfer** [comment]
I see I did an error after debugging #256 for several hours today. Seems like it doesn't correspond to the name luckily. 
I tried recreating the scenario from #256 in an example. Seems like I wasn't successfull by doing so. 
Sry for a wrong issue.
