### ISSUE TITLE
100% processor utilisation if timer is canceled

### ISSUE THREAD

**Issue by ArkturusMengsk** [ros2/rclcpp#319]
As soon as a wall timer is canceled, the processor load will grow immediately to 100%.

`myTimer = this->create_wall_timer(1s, std::bind(&TestNode::timeout, this));`
`myTimer->cancel();`

**Comment by dirk-thomas** [comment]
Please provide a complete example (see http://sscce.org).

**Comment by ArkturusMengsk** [comment]
That is nearly all, that is needed to reproduce the described behavior.

main.cpp
```
#include <rclcpp/rclcpp.hpp>
#include "testnode.h"
int main( int argc, char *argv[] ) {
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<TestNode>());
  return 0;
}
```

testnode.h
```
#ifndef TESTNODE_H
#define TESTNODE_H
#include "rclcpp/rclcpp.hpp"
class TestNode : public rclcpp::Node {
  public:
    TestNode();
  private:
    void timeout();
    rclcpp::TimerBase::SharedPtr  myTimer;
};
#endif
```

testnode.cpp
```
#include <chrono>
#include "testnode.h"
using namespace std::chrono_literals;
TestNode::TestNode() : Node("TestNode") {
  myTimer = this->create_wall_timer(1s, std::bind(&TestNode::timeout, this));
  myTimer->cancel();
}
void TestNode::timeout() {  printf("timeout\n"); }
```

**Comment by mikaelarguedas** [comment]
@ros2/team please try to reproduce and comment here

**Comment by mikaelarguedas** [comment]
@wjwwood to see if recent changes fixed this

**Comment by wjwwood** [comment]
@ArkturusMengsk I was able to reproduce this (thanks for the minimal example!) and we came up with a fix in https://github.com/ros2/rcl/pull/163.

Thanks again for helping us narrow it down, and sorry it took us so long to get to it.

**Comment by mikaelarguedas** [comment]
I'm going to close thins now that ros2/rcl#163 has been merged. Thanks again @ArkturusMengsk for the original report and the reproducible example!
