### ISSUE TITLE
TestStateMachineInfo.available_transitions test flaky

### ISSUE THREAD

**Issue by dhood** [ros2/rclcpp#324]
This test has failed on 93 out of the past 100 of the linux "repeated" nightly jobs.

e.g. http://ci.ros2.org/job/nightly_linux_repeated/624/testReport/junit/(root)/TestStateMachineInfo/available_transitions/

It has also failed twice on OSX (jobs 603 and 622, both mini2). Is it possible there's a race condition?

**Comment by Karsten1987** [comment]
The lifecycle implementation needs a general overlook. There are no rmw_allocators used and some functions definitely deserve a "__attribute__((warn_unused_result))" .

Do you have an idea when this flakiness started?

**Comment by dhood** [comment]
since Dec 15 (http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/499/) which I think is when it was initially added

**Comment by Karsten1987** [comment]
I believe that can be closed, right?

**Comment by dhood** [comment]
Could you reference the changes that would have fixed it? It did still fail [11 days ago](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/663/), but maybe the changes are more recent

**Comment by Karsten1987** [comment]
I believe this fixed it:
https://github.com/ros2/rclcpp/pull/327

It was committed 11days ago :)

**Comment by dhood** [comment]
looks like it worked then!
