### ISSUE TITLE
Unexpected behavior of rclcpp_lifecycle::Transition.label() and rclcpp_lifecycle::State.label()

### ISSUE THREAD

**Issue by breh** [ros2/rclcpp#329]
I'm playing with lifecycle transitions and trying to use Transition and State objects. Unfortunately I'm seeing weird behaviors when it comes to dealing with labels in those objects. 

Looks like the way how label strings are handled is not correct - the constructor takes a string reference and then it passes the pointer to the underlying string using c_str() to the actual handle holding the label. Unfortunately since the constructor parameter is a reference and the constructor only assigns a pointer to the underlying char* buffer, it might cause issues when the original string gets deleted / destroyed and thus the label being corrupted in the underlying structure. 

I believe the proper solution should be to copy the actual characters instead of just assigning the pointer.

**Comment by Karsten1987** [comment]
Thanks for reporting it, I ran into it earlier this week and hopefully patched it in https://github.com/ros2/rclcpp/pull/327

This is going to be merged hopefully soon.

**Comment by breh** [comment]
Great, thanks. Will try to verify tomorrow or next week :).

**Comment by Karsten1987** [comment]
@breh Did that work for you?

**Comment by Karsten1987** [comment]
I am closing this, assuming it worked out for you as well.
Please feel free to re-open or post comment on this ticket.
