### ISSUE TITLE
use of functors in publisher_factory.cpp

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rclcpp#432]
Hi,
Is there any design related reasons for which functors ( std::function() ) are used in rclcpp/publisher_factory.cpp (https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/publisher_factory.hpp)  instead of function templates ? 
The link https://stackoverflow.com/questions/14677997/stdfunction-vs-template describes that functors are slow at runtime. I am curious to know the reason for  choosing  functors, since the rest of the rclcpp code is relying on templates mostly.

**Comment by wjwwood** [comment]
We need `std::function` to support lambda's with captured variables as well as `std::bind`. We also need to store various types of callbacks but call them uniformly.

It's possible we could have an alternative signature that uses a function template, for simple cases (function pointer to a free function). However, it looks like most compilers make this optimization for you (`std::function` has no, or reduced, overhead for simple function pointers), see this answer:

https://stackoverflow.com/a/15045156

If you think it would help to have a non-`std::function` version, then I'd encourage you to open a pr with a prototype and some performance metrics showing some improvement.

I'll close this for now, but I can reopen it if there are follow up action items.
