### ISSUE TITLE
rclcpp logging still uses fprintf

### ISSUE THREAD

**Issue by guillaumeautran** [ros2/rclcpp#438]
rclcpp logging still uses fprintf all over the place. We should align the logging with the standard RCLUTILS_LOG_XXX macros.

**Comment by wjwwood** [comment]
Indeed that's a good goal, though I think @dhood might have been waiting to resolve some lingering logging pr's before doing this? Maybe not. Either way, help is appreciated.

**Comment by dhood** [comment]
nah, I just added some logging, didn't convert all of the existing print statements

**Comment by wjwwood** [comment]
Cool, then just something that needs to be done. I put the "help wanted" tag on it.

**Comment by guillaumeautran** [comment]
I've got a patch almost ready to go (doing some testing). Will push it up soon.

**Comment by dhood** [comment]
closed by https://github.com/ros2/rclcpp/pull/439

**Comment by mikaelarguedas** [comment]
What should we do for the commented out (f)printf calls still in the repo?
There seem to also be some printf still in use for the signal handlers.

**Comment by dhood** [comment]
> What should we do for the commented out (f)printf calls still in the repo?

I imagine it will be updated when [that TODO](https://github.com/ros2/rclcpp/commit/49e9ed34b30202a98fd5aa825130e910dc813d34) gets addressed (unless you're speaking about something else)

> There seem to also be some printf still in use for the signal handlers.
Also has a [todo](https://github.com/ros2/rclcpp/blob/07e5be76218bd830c787b1d5c4af12e9eb6d5f6e/rclcpp/src/rclcpp/utilities.cpp#L138) that would need a decision (and it would need to update the behaviour on launch_testing if we swap) which I didn't think was included in the scope of this PR, but perhaps it was.

**Comment by mikaelarguedas** [comment]
> I imagine it will be updated when that TODO gets addressed (unless you're speaking about something else)

It seems that we can easily miss it when we adress the TODO as the TODO doesnt mention it.
https://github.com/ros2/rclcpp/pull/466
