### ISSUE TITLE
Access violation in new test_utilities test

### ISSUE THREAD

**Issue by dhood** [ros2/rclcpp#458]
See for example https://ci.ros2.org/view/nightly/job/nightly_win_rep/1034/testReport/junit/(root)/projectroot/test_utilities/
```
-- run_test.py: invoking following command in 'C:\J\workspace\nightly_win_rep\ws\src\ros2\rclcpp\rclcpp':
 - C:/J/workspace/nightly_win_rep/ws/build/rclcpp/Release/test_utilities.exe --gtest_output=xml:C:/J/workspace/nightly_win_rep/ws/build/rclcpp/test_results/rclcpp/test_utilities.gtest.xml
-- run_test.py: return code 3221225477
```

RC 3221225477 is [access violation](http://www.febooti.com/products/automation-workshop/online-help/events/run-dos-cmd-command/exit-codes/), so there is likely a bug in the memory usage of this PR https://github.com/ros2/rclcpp/pull/454 or its counterpart in `rcl`

For reference, we have seen a similar issue in the past: https://github.com/ros2/build_cop/issues/19 and the fix boiled down to this PR: https://github.com/ros2/rmw_fastrtps/pull/106/files

FYI @mjcarroll; you may have the best idea of where to look for the issue if you get a chance.

**Comment by mjcarroll** [comment]
Address Sanitize seems to indicate some issues, tracking down the source now.
