### ISSUE TITLE
ros::NodeHandle::resolveName() like function  in rclcpp::Node ?

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rclcpp#460]
## Feature Request 

Does the rclcpp::Node class support the resolveName function ( similar to ros::NodeHandle::resolveName) ?
If not , I would be happy to submit a PR on this.

**Comment by sandiprakhasiya** [comment]
Is there any update on an alternative for the same in ROS2?

**Comment by DLu** [comment]
Similar functionality exists in Galactic/Rolling: https://github.com/ros2/rclcpp/pull/1410

**Comment by fujitatomoya** [comment]
@clalancette @ivanpauno @DLu I think we can close this one.

**Comment by ivanpauno** [comment]
Closing, as I think #1410 completed this feature request.
Feel free to reopen or create a new issue if that's not the case.
