### ISSUE TITLE
/clock topic should have same type as in ROS 1

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclcpp#473]
It should be `rosgraph_msgs/Clock` rather than `rcl_interfaces/Time`.

**Comment by ernestmc** [comment]
@tfoote this is important to bridge Gazebo with ROS2. Do you think it's an easy solution or are there design issues involved?

**Comment by tfoote** [comment]
Yeah, there's no technical reason. I proposed making the message the same as in ROS1 shortly before ardent but we were approaching the code freeze and we'll need to do a global search and replace in the codebase to match this change.

**Comment by dirk-thomas** [comment]
Addressed by #474.
