### ISSUE TITLE
Impossible to tell which parameters were gotten if some don't exist

### ISSUE THREAD

**Issue by sloretz** [ros2/rclcpp#490]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  -  source
- Version or commit hash:
  - 2cb890e1f235af3ba110dc0e44eb30f50a7f2285
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```
ros2 run demo_nodes_cpp listener
```

In another terminal
```
ros2 param set listener bool_param1 true
ros2 param set listener bool_param2 true
ros2 service call /listener/get_parameters rcl_interfaces/GetParameters "{'names': ['bool_param1', 'does_not_exist', 'bool_param2']}"
```

#### Expected behavior

I would expect the returned output from the service call to indicate which parameter did not exist

#### Actual behavior

Response to service call has 2 values, but no indication of which of the 3 requested parameters were returned.

```
rcl_interfaces.srv.GetParameters_Response(values=[rcl_interfaces.msg.ParameterValue(type=1, bool_value=True, integer_value=0, double_value=0.0, string_value='', byte_array_value=[], bool_array_value=[], integer_array_value=[], double_array_value=[], string_array_value=[]), rcl_interfaces.msg.ParameterValue(type=1, bool_value=True, integer_value=0, double_value=0.0, string_value='', byte_array_value=[], bool_array_value=[], integer_array_value=[], double_array_value=[], string_array_value=[])])
```

#### Additional information

The cause seems to be this code that only adds a result if the parameter exists. One solution might be to add an else case adding a parameter value with type `NOT_SET` to the result.

https://github.com/ros2/rclcpp/blob/2a17232ad0c5b54fabea0bc10f4575428f7c7227/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L126-L132

**Comment by dirk-thomas** [comment]
> One solution might be to add an else case adding a parameter value with type `NOT_SET` to the result.

Based on the documentation of the service interface that is exactly what needs to happen: https://github.com/ros2/rcl_interfaces/blob/8e826d4342a70a17358a27bcf384f695ad32cefd/rcl_interfaces/srv/GetParameters.srv#L7
