### ISSUE TITLE
avoid redundant memory allocations in wait_for_work

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#5]
This function, `wait_for_work` which is in the `rclcpp::Executor` class:

- https://github.com/ros2/rclcpp/blob/860f47829492c2c2c5441ae8e41e4478eebc202d/rclcpp/include/rclcpp/executor.hpp#L167
- TODO's:
 - https://github.com/ros2/rclcpp/blob/860f47829492c2c2c5441ae8e41e4478eebc202d/rclcpp/include/rclcpp/executor.hpp#L211
 - https://github.com/ros2/rclcpp/blob/860f47829492c2c2c5441ae8e41e4478eebc202d/rclcpp/include/rclcpp/executor.hpp#L233

repeatedly `malloc`'s for temporary storage used in the `ros_middleware_interface::wait` function.

This could be avoided either by only allocating memory when resizing of the structures is required or by always using a structure of the maximum possible size (still would need to be updated when nodes are added or removed but less frequently) and ensuring that the `ros_middleware_interface::wait` function properly handles the extra, unused storage.

**Comment by jacquelinekay** [comment]
This was resolved by https://github.com/ros2/rclcpp/pull/56, correct?

**Comment by wjwwood** [comment]
I don't think so because we still `malloc` and `free` each time we go through the loop. I think to resolve this ticket we need to have the default memory strategy only `malloc` or `realloc` when there is not enough space, otherwise reusing memory already allocated.

**Comment by jacquelinekay** [comment]
Fixed by #129
