### ISSUE TITLE
Subscriptions are not triggered sometimes

### ISSUE THREAD

**Issue by esteve** [ros2/rclcpp#52]
In the parameter events examples, the callback function is not always triggered. However further testing shows that the data was received, but the executor didn't trigger the callback. This may indicate that there's an issue in the way SingleThreadedExceutor is used.

**Comment by gerkey** [comment]
Happens in OpenSplice and Connext, so it's likely in our code somewhere.  Consider writing a test that reproduces the problem.  Also walk somebody else on the team through the problem.

**Comment by dirk-thomas** [comment]
The same fix as implemented for subscriptions (https://github.com/ros2/rmw_connext/pull/62 https://github.com/ros2/rmw_opensplice/pull/57) needs to be applied for server and client.

**Comment by dirk-thomas** [comment]
We will try to write a test which fails before and passes afterwards. E.g. similar to the subscription: calling two services, spin and likely the second request is never handled.

**Comment by dirk-thomas** [comment]
I implemented the test in ros2/system_tests#45.

**Comment by dirk-thomas** [comment]
@esteve Can you please test the original problem related to parameter events again with the patches being merged and either close this ticket or fill in more information what still doesn't work.
