### ISSUE TITLE
Clock Jump callbacks on System or Steady time?

### ISSUE THREAD

**Issue by sloretz** [ros2/rclcpp#528]
Currently time jump callbacks are registered via [Clock::create_jump_handler()](https://github.com/ros2/rclcpp/blob/4ddb76f466d331e4ca8ff4df7ba25a5dce8496af/rclcpp/include/rclcpp/clock.hpp#L115-L120). Jump handlers are only invoked by [TimeSource::set_clock()](https://github.com/ros2/rclcpp/blob/4ddb76f466d331e4ca8ff4df7ba25a5dce8496af/rclcpp/src/rclcpp/time_source.cpp#L146-L149). This is only called if the clock type is `RCL_ROS_TIME` and ROS time is active.

System clock can jump too. I don't see a way to get notified of this in linux, [though there have been proposed patches to add a syscall](https://lkml.org/lkml/2010/11/11/353). Windows has [WM_TIMECHANGE](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/wm-timechange), but I'm not sure if a GUI window is needed to receive it. OSX has [NSSystemClockDidChangeNotification](https://developer.apple.com/documentation/foundation/nssystemclockdidchangenotification?language=objc), but that's using Objective-C.

As far as I know steady clock can never jump, so maybe `create_jump_handler()` should throw when the clock type is `RCL_STEADY_TIME`?

**Comment by clalancette** [comment]
Given that I don't think there is any work to do here, I'm going to close this out.  If you disagree, please feel free to reopen.

**Comment by peci1** [comment]
I still think having notifications on system time jumps would be beneficial.

A concrete example: our robots are composed of multiple PCs. One of them is the time leader which uses NTP to slowly adjust its clock to the network time. This computer always has RTC, so there are no big problems expected here. However, the secondary PCs are not guaranteed to have RTC and their system clock is controlled via PTP to get their time domain very close to the leader's one. This PTP is allowed to do one jump on the start of the synchronization, which is much better than slowly trying to slew the 1.7 Gs time difference for those who start in zero time. If some code starts before this time jump happens, many things can go wrong.

I thinks what could be done implementation-wide would be a thread with a steady timer just checking current time, e.g. once a second. If it registers a discrepancy, it would trigger the jump callback. Would this be acceptable?

**Comment by jmachowinski** [comment]
We solve issues like this, by waiting after bootup, until we reached ptp sync, and then start our stack.
