### ISSUE TITLE
Setting `use_sim_time` on one node enables ros time on all nodes

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rclcpp#537]
## Bug report

**Required Info:**
- Client library:
  - rclcpp https://github.com/ros2/rclcpp/commit/45d74ba4dc53399325137be4e691d5b7d575baaf

#### Steps to reproduce issue

Add a print in the time source onparameter_event callback by applying this patch to rclcpp
```patch
diff --git a/rclcpp/src/rclcpp/time_source.cpp b/rclcpp/src/rclcpp/time_source.cpp
index bfd0ea2..0952d85 100644
--- a/rclcpp/src/rclcpp/time_source.cpp
+++ b/rclcpp/src/rclcpp/time_source.cpp
@@ -225,9 +225,11 @@ void TimeSource::on_parameter_event(const rcl_interfaces::msg::ParameterEvent::S
     }
     if (it.second->value.bool_value) {
       parameter_state_ = SET_TRUE;
+      RCUTILS_LOG_ERROR("enabling ros time!")
       enable_ros_time();
     } else {
       parameter_state_ = SET_FALSE;
+      RCUTILS_LOG_ERROR("disabling ros time!")
       disable_ros_time();
     }
   }
```

Shell 1: run a C++ listener:
```
ros2 run demo_nodes_cpp listener
```

Shell 2: run another C++ node:
```
ros2 run demo_nodes_cpp add_two_ints_server
```

Shell 3:
Set `use_sim_time` on the listener:
```
$ ros2 param set listener use_sim_time true
Set parameter successful
```

#### Expected behavior
Shell 1 should print:
```
[ERROR] []: enabling ros time!
```

Shell 2 should **not** print anything

#### Actual behavior
Both shells print
```
[ERROR] []: enabling ros time!
```

#### Additional information

This is due to the fact that:
- `/parameter_events` is a global topic and its messages don't contain any node specific information. We could:
   - add information about the node in the message (see https://github.com/ros2/rcl_interfaces/pull/27 for a proposal)
   - make the `parameter_events` topic namespaced on the nodes (discussed in https://github.com/ros2/ros2/issues/432)
- rclcpp is listening to `parameter_events` and parsing its data to know what's hosted on the same node. It should instead leverage its own parameter server (created in all nodes by default) to get notified when a new value of `use_sim_time` has been set

**Comment by crdelsey** [comment]
This seems to be a problem for parameters in general, but for `use_sim_time`, I've been finding this issue to be convenient. In my use cases, I'm either running in real time or simulation, never both at the same time. Being able to set use_sim_time on one node and have the whole system switch has been more convenient that trying to enumerate all nodes and switch them all with separate commands.

It seems if we get parameters like use_sim_time scoped to nodes, there still needs to be a way to switch the whole system to simulation mode at once, possibly triggered by the presence of gazebo

**Comment by wjwwood** [comment]
I think this is addressed with https://github.com/ros2/rcl_interfaces/pull/51?

> Being able to set use_sim_time on one node and have the whole system switch has been more convenient that trying to enumerate all nodes and switch them all with separate commands.

I think that's better left to the configuration management system, e.g. having `launch` set all nodes based on one setting from the user.

**Comment by Darkproduct** [comment]
I just found this: https://answers.ros.org/question/368802/ros2-set-parameters-from-file-and-directly/?answer=369015#post-id-369015

> For example, to set the ROS parameter use_sim_time for all nodes in a launch file, you can something like
```python3
import launch
import launch_ros.actions

def generate_launch_description():
    return launch.LaunchDescription([
        launch_ros.actions.SetParameter(name='use_sim_time', value=True),
        # 'use_sim_time' will be set on all nodes following the line above
    ])
```

Havn't tested this yet.
