### ISSUE TITLE
[rclcpp_lifecycle] introduce new service for valid transitions to call

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rclcpp#550]
see discourse discussion here: https://answers.ros.org/question/302402/ros2cli-lifecycle-shutdown-transition/

**Comment by dirk-thomas** [comment]
Beside the three PRs updating `ros2lifecycle` (`list` -> `nodes` and a new `list` showing the available transitions from the current state) and this looks :top:

**Comment by Karsten1987** [comment]
CI:

[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5256)](https://ci.ros2.org/job/ci_windows/5256/)
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5277)](https://ci.ros2.org/job/ci_linux/5277/)
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4393)](https://ci.ros2.org/job/ci_osx/4393/)

**Comment by Karsten1987** [comment]
@Myzhar Do you mind having a look at this and let me know if this meets your expectations? I believe you have quite some experiences with the lifecycle implementation by now (given that you have been vocal about it on github and discourse). 

The set of patches (branch `lifecycle_refactor`) implements a new service to get all available transitions for the current state as well as a service to introspect the state machine completely.

**Comment by Myzhar** [comment]
I will look at it with very pleasure and will let you know

**Comment by Myzhar** [comment]
@Karsten1987 I need a few suggestion on how to update my workspace with the patches introduced with the `lifecycle_refactor` branch

**Comment by Karsten1987** [comment]
so essentially you want to checkout the branches, right?

So in your workspace you can run the following command to do so:
```
vcs custom --git --args checkout lifecycle_refactor
```

If not, you should be able to go into each referenced repository and change the git branch manually. 
These are:

* demos
* rclcpp
* rcl
* rcl_interfaces
* ros2lifecycle

**Comment by Myzhar** [comment]
Ok, from Waffle I found the list of repositories that have been patched:
- ros2/ros2cli
- ros2/rcl_interfaces
- ros2/demos
- ros2/rcl
- ros2/rclcpp

I launched a `git checkout` manually (I'm sure that a better method exists) for all of them and I was able to compile.

I modified the ocde of my node to follow the new returns type and the other modifications and I finally noticed that the command:
`$ ros2 lifecycle set /zed/zed_node shutdown`
works :+1: 

This is also a very useful command:
```
$ ros2 lifecycle list /zed/zed_node 
- cleanup [2]
	Start: inactive
	Goal: cleaningup
- activate [3]
	Start: inactive
	Goal: activating
- shutdown [51]
	Start: inactive
	Goal: shuttingdown
```

I tried also to understand what kind of other modifications you have introduced, to see if I can get enhancements at code level, but it's not easy.

**Comment by Karsten1987** [comment]
We do have the code review, so don't worry too much about that. It was more like to ask whether that gives you a solution to the issue you posted on discourse.
But then I'll take it, that it indeed works for you as well.

**Comment by Karsten1987** [comment]
So from what I understand is that you want to shutdown the camera either when `deactivate` or `cleanup` is called? In both cases you have a callback for this.
Everything which is happening in other threads has to be manually managed. The callbacks are solely a trigger for it if you want.

Nevertheless, I am going to merge this then as it seems to fulfill the requirements described in your discourse post.
