### ISSUE TITLE
Compiler error pointing to rclcpp::Node

### ISSUE THREAD

**Issue by abylikhsanov** [ros2/rclcpp#590]
Required Info:

Operating System:
Ubuntu 18.04
To reproduce the error: Simply follow the installation of nav2 [here](https://github.com/ros-planning/navigation2/blob/master/doc/BUILD.md)

After trying to compile the nav2 packages, I get this error (from nav2_dynamic_params):

```
navigation2/nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp:240:29: error: ‘using element_type = class rclcpp::Node {aka class rclcpp::Node}’ has no member named ‘get_node_names’; did you mean ‘get_name’?
     auto node_list = node_->get_node_names();
                             ^~~~~~~~~~~~~~
                             get_name
/home/ikhsanov/ws/navigation2_ws/src/navigation2/nav2_dynamic_params/include/nav2_dynamic_params/dynamic_params_client.hpp:243:35: error: unable to deduce ‘auto&&’ from ‘node_list’
     for (const auto & node_name : node_list) {

```

I think it is related to rclcpp as it complains that Node has no member function get_node_names() but I just checked now and it does have the member function. What is going on?

**Comment by dirk-thomas** [comment]
Please fill the ticket in the repository which contains the instructions. There is nothing we can do here in this repo. The function only exists on the master branch - but not in the Bouncy release: https://github.com/ros2/rclcpp/blob/27b0428f7a46d95c1f39494b2c2d98df04bd5576/rclcpp/include/rclcpp/node.hpp#L367
