### ISSUE TITLE
add configurations for parameter events

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#591]
It should be possible to:

- disable the parameter event publisher
- control the QoS settings for the parameter event publisher
  - See: https://github.com/ros2/rclcpp/blob/27b0428f7a46d95c1f39494b2c2d98df04bd5576/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L56

**Comment by rarvolt** [comment]
First time contributing to this project. I'd like to take this issue and already written some code. Should I create Pull Request to this issue to discuss changes or publish them somewhere else?

**Comment by dirk-thomas** [comment]
> Should I create Pull Request to this issue to discuss changes ...

Absolutely, please go ahead and create a pull request.

**Comment by wjwwood** [comment]
I believe this is done as of #614.
