### ISSUE TITLE
timers: consider implementation of timers which uses wait thread

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#6]
Currently timers are naively implemented using a thread per timer, but it should be possible to implement the timers using a timeout argument to the `ros_middleware_interface::wait` function. This would potentially be much more efficient and at least more ellegant, as the total number of threads and `ros_middleware_interface::GuardConditionHandle`'s would be significantly reduced. A stepping stone to this, without requiring a timeout in the `ros_middleware_interface::wait` function, would be to have one thread for all timers which does the same waiting mechanism, but using a sleep function not as a parameter to `ros_middleware_interface::wait`.

**Comment by jacquelinekay** [comment]
Assigning this to myself and thinking about it this week because of its relationship to real-time performance.
