### ISSUE TITLE
Abnormal termination after SIGINT

### ISSUE THREAD

**Issue by hidmic** [ros2/rclcpp#610]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Bionic 18.04 (as in [Nvidia OpenGL Docker image](https://hub.docker.com/r/nvidia/opengl/))
- Installation type:
  - Binary (debs)
- Version or commit hash:
  - Crystal pre-release.
- DDS implementation:
  - ADLink OpenSplice 6.9
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Run and Ctrl+C the following command a few times:
```sh
RMW_IMPLEMENTATION=rmw_opensplice_cpp ros2 run image_tools cam2image
```
#### Expected behavior
Normal termination upon SIGINT receival.
#### Actual behavior
Sporadically, it shows:
```sh
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  Failed to create interrupt guard condition in Executor constructor: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-crystal-rcl-0.6.1/src/rcl/guard_condition.c:69
```
#### Additional information

May be related to #604.

**Comment by ivanpauno** [comment]
Closing in favor of https://github.com/ros2/rclcpp/issues/1139, which has a more recent discussion.
