### ISSUE TITLE
Lifecycle node class is missing parameter-related templates

### ISSUE THREAD

**Issue by mjeronimo** [ros2/rclcpp#642]
#### Feature description

The LifecycleNode class is missing several parameter-related templates that are present in the regular Node class, such as get_parameter_or, get_parameter_or_set, and set_parameter_if_not_set. Adding the missing templates would allow a lifecycle node to be equivalent to normal nodes in its parameter-handling functionality, making it easier to port from a Node to a LifecycleNode.  

#### Implementation considerations

Should be able to copy/paste the templates from the Node header.

**Comment by Karsten1987** [comment]
thanks for reporting. The implementation considerations make sense to me given that the lifecycle node has a lot of function forwarding already.

**Comment by jacobperron** [comment]
@Karsten1987 I think this has been resolved by #645. Please re-open if I'm mistaken.
