### ISSUE TITLE
cppcheck warning in clock.cpp

### ISSUE THREAD

**Issue by hidmic** [ros2/rclcpp#644]
## Bug report

**Required Info:**

- Operating System:
  - MacOS (Sierra? As in CI nodes)
- Installation type:
  - From source
- Version or commit hash:
  - Current master @ https://github.com/ros2/rclcpp/commit/3919ab189795fbf47b5427add06f45d8a43f81ce

#### Additional information

See https://ci.ros2.org/job/ci_osx/5178/testReport/junit/rclcpp/cppcheck/warning__nullPointer__src_rclcpp_clock_cpp_139_/.

**Comment by sloretz** [comment]
fixed by #646
