### ISSUE TITLE
ROS2 bag record issue

### ISSUE THREAD

**Issue by JoltonDsouza** [ros2/rclcpp#663]
I have a custom ROS2 message, which I built and sourced correctly and it successfully publishes and subscribes on the node I create. However, when I try to record the bag files using,

> ros2 bag record -topicname

it throws this error,

> Failed to record: Something went wrong loading the typesupport library for message type package_name/msgname. Library could not be found.

I don't know why this error, is it because it is a custom message? Or is it because I need to link the custom messages somewhere?

**Comment by Karsten1987** [comment]
I am closing this in favor of ros2/rosbag2#95, because `rclcpp` is not a related package to the issue reported.
