### ISSUE TITLE
Hang in MultiThreadedExecutor::run()

### ISSUE THREAD

**Issue by malsbat** [ros2/rclcpp#835]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - from source
- Version or commit hash:
  - 4feecc594559927cdc7689f5e73c6f210608aebc
- DDS implementation:
  - DPS, Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Run test_multithreaded__rmw_dps_cpp.multi_access_publisher in a loop until it hangs.  I can reproduce this frequently with rmw_dps and less frequently with rmw_fastrtps. 
```
while gtest_multithreaded__rmw_dps_cpp --gtest_filter=test_multithreaded__rmw_dps_cpp.multi_access_publisher; do echo $?; done
```

#### Expected behavior
The test does not hang.

#### Actual behavior
The test hangs.

#### Additional information

I believe the following is what is happening inside MultiThreadedExecutor::run():
1. Thread A gets a timer callback.  This sets the callback group's can_be_taken_from to false and inserts the timer into scheduled_timers_.
2. Thread B then tries to get the next callback, but can_be_taken_from is false, so it calls rmw_wait.
3. Thread A executes the callback.  This sets can_be_taken_from to true and wakes up thread B.
4. Thread B wakes up, gets the next callback but sees that it is the timer in scheduled_timers_ so continues.  The lock is released but before the AnyExecutable destructor is run.
5. Thread C gets the lock and tries to get the next executable.  The group's can_be_taken_from is false so it calls rmw_wait.
6. Thread B runs calling the AnyExecutable destructor, setting can_be_taken_from to true but not triggering the guard condition.
7. Thread A tries to get the wait_mutex_ to clear the scheduled_timer_, but B has the lock and is waiting to be triggered.

**Comment by ivanpauno** [comment]
Fixed in #836, closing!
