### ISSUE TITLE
move rmw_implementation?

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclcpp#9]
I think it made sense for `rmw_implementation` to be in the `rclcpp` repository when it only used by `rclcpp`, but now I think it probably belongs in `rmw`.

Thoughts?

**Comment by dirk-thomas** [comment]
Since `rmw_implementation` is unrelated to and does not depend on any client library I would choose the `rmw` repository instead of `rclcpp`.

**Comment by wjwwood** [comment]
Ok, unless someone disagrees I'll create a card for that and do it this sprint.
