### ISSUE TITLE
Action client unnecessarily creates an event every time wait_for_action_server is called

### ISSUE THREAD

**Issue by astere-cpr** [ros2/rclcpp#919]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - from source
- Version or commit hash:
  - b92db52bb14ec097946bfe44d2b337359dddfbab
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Create an action client to connect to an existing running action server and call `wait_for_action_server()' in a loop 

#### Expected behavior

The number reported by calling `count_graph_users()' should not increase

#### Actual behavior

The number increases steadily.

#### Additional information

Each call to `wait_for_action_server` adds an event to the node's graph listener event list. If no graph change events occur that vector will increase indefinitely.

**Comment by jacobperron** [comment]
Fixed in #920
