### ISSUE TITLE
Add synchronous call method to Client

### ISSUE THREAD

**Issue by Shivlocin** [ros2/rclcpp#975]
#### Feature description

Currently I have to use a lot of boilerplate code to implement a service request in a node which is being spun by an executor.

Example:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create srv request
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;populate request
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;call async_send_request (returns future)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;call std::future wait_for (prevent blocking indefinitely)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assess return value (ready, timeout, etc)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perform work accordingly 

#### Implementation considerations

I propose adding a function to the client class which would take the request and a timeout value as arguments and return pair (bool or future status & the future) as appropriate.  

Proposed function would handle:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;call async_send_request
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;call std::future wait_for(timeout)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return wait_for result & the future

**Comment by jacobperron** [comment]
I think you are describing a synchronous send request method, which sounds like a reasonable API to add. [`rclpy` has a synchronous method](https://github.com/ros2/rclpy/blob/822f19406de40f9e7df0c73aa4d52837a42bcfde/rclpy/rclpy/client.py#L67) as well.

Suggestion: instead of returning the future status and future, we can return the service response directly. In the event of a timeout we can raise an exception.

**Comment by Shivlocin** [comment]
A synchronous request is exactly what I'm looking for, thank you.

**Comment by jacobperron** [comment]
@Shivlocin If you would like to implement a synchronous method, I'm happy to review a pull request :)

**Comment by Shivlocin** [comment]
I'll happily have a go at it. More to follow.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/synchronous-request-to-service-in-callback-results-in-deadlock/12767/3

**Comment by tonynajjar** [comment]
Should this be closed as a duplicate to https://github.com/ros2/rclcpp/issues/1533? The other PR has more information/debate

**Comment by clalancette** [comment]
Yes, that's a good point.  I will close this one.
